### ISSUE TITLE
Issue running make in terminal 

### ISSUE THREAD

**Issue by corinne-riddell** [ebenmichael/policy-trial-emulation#1]
Hi! I'm trying to run the two make lines of code you specify on your README but getting the error printed below (note I redacted my IP address below). Any ideas how I can solve this? 🙏 thanks!

Cloning into 'covid-19-data'...
Warning: Permanently added the RSA host key for IP address '[REDACTED]' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
make: *** [data/covid-19-data] Error 128

**Comment by ebenmichael** [comment]
The issue is that the Makefile clones the NYT repository via ssh. Look [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh) to see how to add an ssh key to your GitHub account.

Alternatively, to clone over https you can change [line 6 in the Makefile](https://github.com/ebenmichael/policy-trial-emulation/blob/5275b83617413e679aa0f2a1216bdcf91a685c73/Makefile#L6) to 

`cd data && git clone https://github.com/nytimes/covid-19-data.git`

but I'm not 100% sure this will work.
